export interface Course {
  courseId: number;
  courseType?: string | null;
  classification?: string | null;
  activityId: number;
  entityId: number;
  introduceDate: string;
  suspensionDate?: string | null;
  courseName: string;
  chargingPattern?: string | null;
  sessionMinutes: number;
  noOfDaysInWeek: number;
  daysPattern?: string | null;
  availabilityPattern: string;
  minEnrollmentUnits: number;
  maxPerson?: number | null;
  batchCapacity: number;
  totalParallelBatches: number;
  minAge: number;
  maxAge: number;
  gender?: "Male" | "Female" | "Any" | null;
  balanceUsable?: string;
  enrApprovalRequired?: boolean;
  CGSTRate?: number;
  SGSTRate?: number;
  status?: string | null;
  createdBy?: number | null;
  createdAt: string;
  updatedAt: string;
}